
default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: artconnect_development 

test:
  <<: *default
  database: artconnect_test

production:
  <<: *default
  database: artconnect_production
  username: artconnect
  password: <%= ENV['ARTCONNECT_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
